name: Publish package
on:
    push:
        branches:
            - main
            - feature/add-npm-on-main
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.17]
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.PACKAGE_SECRET }}
            - name: Check cache
              id: cache
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-0
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'
            - name: install dependencies
              run: npm install
            - name: build code
              run: npm run build
            - name: publish build
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}